-- 1. CREACIÓN DE LA TABLA
-- Definición de la estructura de datos para la carga del CSV
CREATE TABLE hr_employee_data (
    EmployeeNumber INT PRIMARY KEY
    Age SMALLINT NOT NULL CHECK(age BETWEEN 18 OR 100),
    Attrition VARCHAR(10) CHECK('Yes' or 'No'),
    BusinessTravel VARCHAR(50),
    DailyRate INT CHECK(DailyRate >= 0),
    Department VARCHAR (50) NOT NULL,
    DistanceFromHome INT CHECK(DistanceFromHome >= 0),
    Education SMALLINT CHECK(education BETWEEN 1 AND 5),
    EducationField VARCHAR(50),
    EmployeeCount INT,
    EnvironmentSatisfaction SMALLINT CHECK(EvironmenSatisfaction BETWEEN 1 AND 4),
    Gender VARCHAR(10) NOT NULL,
    HourlyRate INT,
    JobInvolvement SMALLINT CHECK(JobInvolvement BETWEEN 1 AND 4),
    JobLevel SMALLINT CHECK(JobLevel BETWEEN 1 AND 5),
    JobRole VARCHAR(50),
    JobSatisfaction SMALLINT CHECK (JobSatisfaction BETWEEN 1 AND 4),
    MaritalStatus VARCHAR(20),
    MonthlyIncome INT NOT NULL CHECK(MonthlyIncome >= 0),
    MonthlyRate INT NOT NULL CHECK(MonthlyRate >= 0),
    NumCompaniesWorked SMALLINT CHECK(NumCompaniesWorked >= 0),
    Over18 VARCHAR(5) NOT NULL,
    OverTime VARCHAR(3) CHECK(OverTime IN ('Yes' OR 'No')),
    PercentSalaryHike SMALLINT CHECK(PercentSalaryHike >= 0),
    PerformanceRating SMALLINT CHECK (PerformanceRating BETWEEN 1 AND 5),
    RelationshipSatisfaction SMALLINT CHECK (RelationshipSatisfaction BETWEEN 1 AND 4),
    StandardHours SMALLINT CHECK(StandardHours >= 0),
    StockOptionLevel SMALLINT CHECK(StockOptionLevel BETWEEN 0 AND 3),
    TotalWorkingYears SMALLINT CHECK (TotalWorkingYears >= 0),
    TrainingTimesLastYear INT CHECK (TrainingTimesLastYear >= 0),
    WorkLifeBalance SMALLINT CHECK(WorkLifeBalance BETWEEN 1 AND 4),
    YearsAtCompany INT CHECK(YearsAtCompany >= 0),
    YearsInCurrentRole INT CHECK(YearsInCurrentRole >= 0),
    YearsSinceLastPromotion INT CHECK(YearsSinceLastPromotion >= 0),
    YearsWithCurrManager INT CHECK(YearsWithCurrManager >= 0)
);

