-- 1. CREACIÓN DE LA TABLA
-- DEFINICIÓN DE LA ESTRUCTURA DE DATOS PARA LA CARGA DEL CSV.
CREATE TABLE hr_employee_data (
    employeenumber INT PRIMARY KEY
    age SMALLINT NOT NULL CHECK(age BETWEEN 18 OR 100),
    attrition VARCHAR(10) CHECK('Yes' or 'No'),
    businesstravel VARCHAR(50),
    dailyrate INT CHECK(dailyrate >= 0),
    department VARCHAR (50) NOT NULL,
    distancefromhome INT NOT NULL CHECK(distancefromhome >= 0),
    education SMALLINT NOT NULL CHECK(education BETWEEN 1 AND 5),
    educationfield VARCHAR(50),
    employeecount INT,
    environmentsatisfaction SMALLINT CHECK(evironmensatisfaction BETWEEN 1 AND 4),
    gender VARCHAR(10) NOT NULL,
    hourlyrate INT,
    jobinvolvement SMALLINT CHECK(jobinvolvement BETWEEN 1 AND 4),
    joblevel SMALLINT CHECK(joblevel BETWEEN 1 AND 5),
    jobrole VARCHAR(50),
    jobsatisfaction SMALLINT CHECK (jobsatisfaction BETWEEN 1 AND 4),
    maritalstatus NOT NULL VARCHAR(20),
    monthlyincome INT NOT NULL CHECK(monthlyincome >= 0),
    monthlyrate INT NOT NULL CHECK(monthlyrate >= 0),
    numcompaniesworked SMALLINT CHECK(numcompaniesworked >= 0),
    over18 VARCHAR(5) NOT NULL,
    overtime VARCHAR(3) NOT NULL CHECK(overtime IN ('Yes' OR 'No')),
    percentsalaryhike SMALLINT CHECK(percentsalaryhike >= 0),
    performancerating SMALLINT CHECK (performancerating BETWEEN 1 AND 5),
    relationshipsatisfaction SMALLINT CHECK (relationshipsatisfaction BETWEEN 1 AND 4),
    standardhours SMALLINT CHECK(standardhours >= 0),
    stockoptionlevel SMALLINT CHECK(stockoptionlevel BETWEEN 0 AND 3),
    totalworkingyears SMALLINT CHECK (totalworkingyears >= 0),
    trainingtimeslastyear INT CHECK (trainingtimeslastYear >= 0),
    worklifebalance SMALLINT CHECK(worklifebalance BETWEEN 1 AND 4),
    yearsatcompany INT CHECK(yearsatcompany >= 0),
    yearsincurrentrole INT CHECK(yearsincurrentrole >= 0),
    yearssincelastpromotion INT CHECK(yearssincelastpromotion >= 0),
    yearswithcurrmanager INT CHECK(yearswithcurrmanager >= 0)
);

