-- 2. VALIDACIÓN DE CALIDAD DE DATOS
-- A. BUSCAMOS FILAS CON INCONSISTENCIAS (VALORES NULOS) EN COLUMNAS CRÍTICAS.

SELECT *
FROM hr_employee_data
WHERE 
    age IS NULL
    OR department IS NULL
    OR jobrole IS NULL
    OR monthlyincome IS NULL;

-- EN CASO DE ENCONTRAR HACEMOS UN UPDATE DE LA TABLA PARA CORREGIR LOS VALORES NULOS
UPDATE hr_employee_data
SET
    age = COALESCE(age, 0),
    monthlyincome = COALESCE(monthlyincome, 0),
    department = COALESCE(department, 'NULO'),
    jobrole = COALESCE(jobrole, 'NULO')
WHERE
    age IS NULL
    OR department IS NULL
    OR jobrole IS NULL
    OR monthlyincome IS NULL;

-- HACEMOS UN COUNT PARA VERIFICAR SI LOS DATOS NULOS DESAPARECIERON.
SELECT COUNT(*) AS datos_nulos
FROM hr_employee_data
WHERE
    age IS NULL
    OR department IS NULL
    OR jobrole IS NULL
    OR monthlyincome IS NULL;

--B. VERIFICAMOS POSIBLES INCONSISTENCIAS DE VALORES DE LA TABLA. AL DESCONOCER LA FUENTE ORIGINAL DEL DATASET NO PODEMOS SABER SI ES CORRECTO O NO, ASÍ QUE ÚNICAMENTE LO ANALIZAMOS Y MARCAMOS, PERO EVITAMOS UNA CORRECCIÓN.

SELECT * 
FROM hr_employee_data
WHERE 
    YearsAtCompany > TotalWorkingYears;

SELECT *
FROM hr_employee_data
WHERE
    YearsInCurrentRole > YearsATCompany;

--C. VERIFICAMOS DATOS MAL CARGADOS EN ATTRITION Y OVERTIME, YA QUE EL CHECK NO VERIFICA ESPACIOS DE MÁS NI LAS MAYÚSCULAS.

-- VERIFICAMOS SI HAY VALORES DIFERENTES A "Yes" O "No".
SELECT DISTINCT Attrition
FROM hr_employee_data

-- EN CASO DE ENCONTRAR REALIZAMOS UN UPDATE DE LA COLUMNA PARA ELIMINAR ESPACIOS DE MÁS Y ASEGURAR QUE TODOS LOS VALORES TENGAN UNA CONSISTENCIA EN EL USO DE LA MAYÚSCULA.
UPDATE hr_employee_data
SET attrition = INITCAP(TRIM(attrition));

--VERIFICAMOS SI HAY VALORES DIFERENTES A "Yes" O "No".
SELECT DISTINCT OverTime
FROM hr_employee_data

-- EN CASO DE ENCONTRAR REALIZAMOS UN UPDATE DE LA COLUMNA PARA ELIMINAR ESPACIOS DE MÁS Y ASEGURAR QUE TODOS LOS VALORES TENGAN UNA CONSISTENCIA EN EL USO DE LA MAYÚSCULA.
UPDATE hr_employee_data
SET OverTime = INITCAP(TRIM(OverTime));
