--3. REALIZAMOS LOS KPIS DESCRIPTIVOS DEL DATASET PARA ENTENDER 

--A. CANTIDAD TOTAL DE EMPLEADOS
SELECT COUNT(*) AS total_empleados 
FROM 

--B. CANTIDAD DE EMPLEADOS QUE DESERTARON 
SELECT COUNT(*) AS empleados_desertados
FROM 
WHERE Attrition = 'Yes'

--C. DISTRIBUCIÓN DE GÉNERO

--D. DEPARTAMENTOS DE LA EMPRESA
