--3. REALIZAMOS LOS KPIS DESCRIPTIVOS DEL DATASET PARA ENTENDER 

--A. CANTIDAD TOTAL DE EMPLEADOS

--B. CANTIDAD DE EMPLEADOS QUE DESERTARON 

--C. GRUPOS DE EDADES 

--E. SALARIO PROMEDIO 

--F. DISTRIBUCIÓN DE GÉNERO

--G. DEPARTAMENTOS DE LA EMPRESA
